[project]
name = "gobangol-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiosqlite>=0.21.0",
    "fastapi>=0.116.1",
    "python-socketio>=5.13.0",
    "rich>=14.1.0",
    "uvicorn>=0.35.0",
]
