/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/admin': RouteRecordInfo<'/admin', '/admin', Record<never, never>, Record<never, never>>,
    '/doc/': RouteRecordInfo<'/doc/', '/doc', Record<never, never>, Record<never, never>>,
    '/doc/api': RouteRecordInfo<'/doc/api', '/doc/api', Record<never, never>, Record<never, never>>,
    '/doc/copyright': RouteRecordInfo<'/doc/copyright', '/doc/copyright', Record<never, never>, Record<never, never>>,
    '/doc/forbidden-move': RouteRecordInfo<'/doc/forbidden-move', '/doc/forbidden-move', Record<never, never>, Record<never, never>>,
    '/doc/gomoku': RouteRecordInfo<'/doc/gomoku', '/doc/gomoku', Record<never, never>, Record<never, never>>,
    '/doc/swap': RouteRecordInfo<'/doc/swap', '/doc/swap', Record<never, never>, Record<never, never>>,
    '/doc/update': RouteRecordInfo<'/doc/update', '/doc/update', Record<never, never>, Record<never, never>>,
    '/game/ol/': RouteRecordInfo<'/game/ol/', '/game/ol', Record<never, never>, Record<never, never>>,
    '/game/ol/play-copy': RouteRecordInfo<'/game/ol/play-copy', '/game/ol/play-copy', Record<never, never>, Record<never, never>>,
    '/game/pve/': RouteRecordInfo<'/game/pve/', '/game/pve', Record<never, never>, Record<never, never>>,
    '/game/pve/play': RouteRecordInfo<'/game/pve/play', '/game/pve/play', Record<never, never>, Record<never, never>>,
    '/game/pvp/': RouteRecordInfo<'/game/pvp/', '/game/pvp', Record<never, never>, Record<never, never>>,
    '/game/pvp/play': RouteRecordInfo<'/game/pvp/play', '/game/pvp/play', Record<never, never>, Record<never, never>>,
    '/setting': RouteRecordInfo<'/setting', '/setting', Record<never, never>, Record<never, never>>,
  }
}
