/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin/': RouteRecordInfo<'/admin/', '/admin', Record<never, never>, Record<never, never>>,
    '/doc/': RouteRecordInfo<'/doc/', '/doc', Record<never, never>, Record<never, never>>,
    '/doc/update': RouteRecordInfo<'/doc/update', '/doc/update', Record<never, never>, Record<never, never>>,
    '/game/ol/': RouteRecordInfo<'/game/ol/', '/game/ol', Record<never, never>, Record<never, never>>,
    '/game/ol/pvp': RouteRecordInfo<'/game/ol/pvp', '/game/ol/pvp', Record<never, never>, Record<never, never>>,
    '/game/pve/': RouteRecordInfo<'/game/pve/', '/game/pve', Record<never, never>, Record<never, never>>,
    '/game/pve/play': RouteRecordInfo<'/game/pve/play', '/game/pve/play', Record<never, never>, Record<never, never>>,
    '/game/pvp/play': RouteRecordInfo<'/game/pvp/play', '/game/pvp/play', Record<never, never>, Record<never, never>>,
    '/room/': RouteRecordInfo<'/room/', '/room', Record<never, never>, Record<never, never>>,
    '/setting': RouteRecordInfo<'/setting', '/setting', Record<never, never>, Record<never, never>>,
  }
}
